name: Doxygen
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Code quality control]
    types: [completed]
    branches:
      - '**'

jobs:
  build:
    name: doxygen
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failed' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Configure
        shell: bash
        run: |
          sudo apt install doxygen
          doxygen Doxyfile
          mv src-gh-pages/html src-gh-pages/docs
      - name: Commit
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src-gh-pages/
          git commit -m "Doxygen output" -a
      - name: Push cppcheck results
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}