name: Build & Test
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened]
  pull_request_target:
    branches:
      - "*"

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest MinGW",
            os: windows-latest,
            cxx: "g++",
          }
          - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            cxx: "g++-11"
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies on windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install mingw --version 11.2.0.07112021 --force
          make --version
          gcc --version
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu Latest GCC')
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11 make
          make --version
          gcc-11 --version
          g++-11 --version
          mkdir -p ./bin
      - name: Configure
        shell: bash
        run: |
          make -B install
      - name: Build
        shell: bash
        run: |
          make -B clean build build_tests COMPILER_CPP=${{ matrix.config.cxx }}
      - name: Prepare speed test
        shell: bash
        run: |
          mkdir -p ./benchmark/performance/${{ matrix.config.os }};
      - name: -O
        if: always()
        shell: bash
        timeout-minutes: 100
        run: |
          make -B clean build_tests run_tests COMPILER_CPP=${{ matrix.config.cxx }} OPTIMIZATION_LEVEL=-O
          cp ./bin/log/performance.txt ./benchmark/performance/${{ matrix.config.os }}performance-O.txt
          cp ./bin/log/performance_summary.txt ./benchmark/performance/${{ matrix.config.os }}performance_summary-O.txt
      - name: -O1
        if: always()
        shell: bash
        timeout-minutes: 100
        run: |
          make -B clean build_tests run_tests COMPILER_CPP=${{ matrix.config.cxx }} OPTIMIZATION_LEVEL=-O1
          cp ./bin/log/performance.txt ./benchmark/performance/${{ matrix.config.os }}performance-O1.txt
          cp ./bin/log/performance_summary.txt ./benchmark/performance/${{ matrix.config.os }}performance_summary-O1.txt
      - name: -O2
        if: always()
        shell: bash
        timeout-minutes: 100
        run: |
          make -B clean build_tests run_tests COMPILER_CPP=${{ matrix.config.cxx }} OPTIMIZATION_LEVEL=-O2
          cp ./bin/log/performance.txt ./benchmark/performance/${{ matrix.config.os }}performance-O2.txt
          cp ./bin/log/performance_summary.txt ./benchmark/performance/${{ matrix.config.os }}performance_summary-O2.txt
      - name: -O3
        if: always()
        shell: bash
        timeout-minutes: 100
        run: |
          make -B clean build_tests run_tests COMPILER_CPP=${{ matrix.config.cxx }} OPTIMIZATION_LEVEL=-O3
          cp ./bin/log/performance.txt ./benchmark/performance/${{ matrix.config.os }}performance-O3.txt
          cp ./bin/log/performance_summary.txt ./benchmark/performance/${{ matrix.config.os }}performance_summary-O3.txt
      - name: -Ofast
        if: always()
        shell: bash
        timeout-minutes: 100
        run: |
          make -B clean build_tests run_tests COMPILER_CPP=${{ matrix.config.cxx }} OPTIMIZATION_LEVEL=-Ofast
          cp ./bin/log/performance.txt ./benchmark/performance/${{ matrix.config.os }}performance-Ofast.txt
          cp ./bin/log/performance_summary.txt ./benchmark/performance/${{ matrix.config.os }}performance_summary-Ofast.txt
      - name: -Og
        if: always()
        shell: bash
        timeout-minutes: 100
        run: |
          make -B clean build_tests run_tests COMPILER_CPP=${{ matrix.config.cxx }} OPTIMIZATION_LEVEL=-Og
          cp ./bin/log/performance.txt ./benchmark/performance/${{ matrix.config.os }}performance-Og.txt
          cp ./bin/log/performance_summary.txt ./benchmark/performance/${{ matrix.config.os }}performance_summary-Og.txt
      - name: -Os
        if: always()
        shell: bash
        timeout-minutes: 100
        run: |
          make -B clean build_tests run_tests COMPILER_CPP=${{ matrix.config.cxx }} OPTIMIZATION_LEVEL=-Os
          cp ./bin/log/performance.txt ./benchmark/performance/${{ matrix.config.os }}performance-Os.txt
          cp ./bin/log/performance_summary.txt ./benchmark/performance/${{ matrix.config.os }}performance_summary-Os.txt
      - name: Summarize
        if: always()
        shell: bash
        timeout-minutes: 100
        run: |
          cat ./benchmark/performance/${{ matrix.config.os }}/performance_summary*
      - name: Commit test results
        if: ${{ github.ref == 'refs/heads/master' && startsWith(matrix.config.name, 'Ubuntu Latest GCC') }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "${{ github.sha }} ${{ matrix.config.os }}" >> benchmark/integration_tests/commit_hash
          rm -rf src-gh-pages
          mkdir -p src-gh-pages/it/
          cp -rf ./benchmark/performance/*/* src-gh-pages/it/
          git add .
          git commit -m "Unit & Integation results" -a
      - name: Push testing results
        if: ${{ startsWith(matrix.config.name, 'Ubuntu Latest GCC') }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}