name: Build & Test
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened]
  pull_request_target:
    branches:
      - "*"

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest MinGW",
            os: windows-latest,
            cxx: "g++",
          }
          - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            cxx: "g++-11"
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies on windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install mingw --version 11.2.0.07112021 --force
          make --version
          gcc --version
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu Latest GCC')
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11 make
          make --version
          gcc-11 --version
          g++-11 --version
          mkdir -p ./bin
      - name: Configure
        shell: bash
        run: |
          make -B install
      - name: Build
        shell: bash
        run: |
          make -B clean build build_tests COMPILER_CPP=${{ matrix.config.cxx }}
      - name: Test
        shell: bash
        timeout-minutes: 10
        run: |
          make -B run_tests
      - name: Commit test score
        if: ${{ github.ref == 'refs/heads/master' && startsWith(matrix.config.name, 'Ubuntu Latest GCC') }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "${{ github.sha }} ${{ matrix.config.os }}" >> benchmark/integration_tests/commit_hash
          rm -rf src-gh-pages
          mkdir -p src-gh-pages/it/
          cp ./bin/log/performance* src-gh-pages/it/
          git add .
          git commit -m "Unit & Integation tests run" -a
      - name: Push testing results
        if: ${{ startsWith(matrix.config.name, 'Ubuntu Latest GCC') }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Speed test based on optimization flags
        shell: bash
        timeout-minutes: 100
        run: |
          make -B local-benchmark COMPILER_CPP=${{ matrix.config.cxx }} DIR_PREFIX=${{ matrix.config.os }}/
          cat ./benchmark/performance/${{ matrix.config.os }}/performance_summary*