run-name: Compile & Build / ${{ github.event.head_commit.message }}
name: Compile & Build
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened]
  pull_request_target:
    branches:
      - "*"

jobs:
  macos-build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11, macos-12, macos-latest]
        inja: [ON, OFF]
    name: MacOS / ${{ matrix.os }} / clang++ / Inja ${{ matrix.inja }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies on ${{ matrix.os }}
        run: |
          brew install llvm cmake
          cmake --version
          clang++ --version
      - name: Configure with Clang
        shell: bash
        run: |
          CXX_COMPILE=clang++ cmake -DUSE_INJA=${{ matrix.inja }} -G 'Unix Makefiles' .
      - name: Build
        shell: bash
        run: |
          make
      - name: Run tests
        shell: bash
        run: |
          ./tests/Core-Tests
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022, windows-latest]
        compiler: [cl, clang++, g++]
        inja: [ON, OFF]
    name: Windows / ${{ matrix.os }} / ${{ matrix.compiler }} / Inja ${{ matrix.inja }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: ilammy/msvc-dev-cmd@v1.4.1
        if: "${{ matrix.compiler }}" == "cl"
      - name: Clang setup
        if: "${{ matrix.compiler }}" == "clang++"
        run: choco install clang
      - name: MinGW setup
        if: "${{ matrix.compiler }}" == "g++"
        run: choco install mingw --version 11.2.0.07112021
      - name: Configure with ${{ matrix.compiler }}
        shell: bash
        run: |
          CXX_COMPILE=${{ matrix.compiler }} cmake -DUSE_INJA=ON -G 'MinGW Makefiles' .
      - name: Build
        shell: bash
        run: |
          make
      - name: Run tests
        shell: bash
        run: |
          ./tests/Core-Tests
  ubuntu-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
        compiler: [clang++, g++]
        inja: [ON, OFF]
    name: Ubuntu / ${{ matrix.os }} / ${{ matrix.compiler }} / Inja ${{ matrix.inja }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Clang setup
        if: "${{ matrix.compiler }}" == "clang++"
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y llvm
      - name: MinGW setup
        if: "${{ matrix.compiler }}" == "g++"
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-11 gcc-11
      - name: Configure with ${{ matrix.compiler }}
        shell: bash
        run: |
          CXX_COMPILE=${{ matrix.compiler }} cmake -DUSE_INJA=ON -G 'MinGW Makefiles' .
      - name: Build
        shell: bash
        run: |
          make
      - name: Run tests
        shell: bash
        run: |
          ./tests/Core-Tests